LIFE/LIFE/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.urls import reverse

from LIFE import settings
from Slife import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home),
    path('Slife/',include('Slife.urls')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


# admin.site.AdminSite.site_header = 'SLife'
# admin.site.AdminSite.site_title = 'SLife'
# admin.site.AdminSite.index_title = 'SLife Admin'



#this code is from bucky
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LIFE/Slife/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from django.urls import reverse

from Slife import views


app_name = 'Slife'
urlpatterns = [
    path('',views.home,name='home'),
    path('register/',views.register,name='register'),
    #path('activate/<uidb64>/<token>/',views.activate, name='activate'),
    path('login/',views.my_login,name='login'),
    path('logout/',views.my_logout,name='logout'),
    path('about/',views.about,name='about'),


    #password reset urls
    path('password-reset/',
    auth_views.PasswordResetView.as_view(template_name='Slife/password_reset_done.html',
    email_template_name='password_reset_email.html ',
    success_url=reverse_lazy('Slife:password_reset_done')),

    name='password_reset'),

   path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='Slife/password_reset_done.html'),
    name='password_reset_done' ),
   path('password-reset-confirm/<uidb64>/<token>/',
   auth_views.PasswordResetConfirmView.as_view(template_name='Slife/password_reset_confirm.html',
                                                             success_url = reverse_lazy('Slife:password_reset_complete')
   ),name='password_reset_complete'), 


    path('categories/all/', views.all_categories,name='categories'),
    path('search/', views.search,name='search'),
    path('contact/', views.contact,name='contact'),
    path('<slug>/', views.options, name='options'),
    path('<slug>/comment/', views.comment, name='comment'),
    path('<slug>/vote/', views.vote, name='vote'),
    path('api/categories', views.api_categories,name='api_categories'),
    path('api/options/', views.api_options,name='api_options'),




]

LIFE/Slife/models.py
# this is a docstring for this AutoSlugField
from autoslug import AutoSlugField
from django.contrib.auth.models import User
from django.db import models
from django.db.models import CASCADE
from django.contrib.auth.admin import UserAdmin
from django.core.validators import MaxLengthValidator, MinValueValidator
from datetime import timedelta as timezone



class Category(models.Model):
    name = models.CharField(max_length=250)
    slug = AutoSlugField(populate_from='name')
    details = models.TextField(blank=True)
    image = models.FileField(blank=True,upload_to='categories')
    views = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now=True)
    modified = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"




class Option(models.Model):
    name = models.CharField(max_length=250)      
    slug = AutoSlugField(populate_from='name')
    image = models.ImageField(blank=True,upload_to='options')
    details = models.TextField(blank=True)
    category = models.ForeignKey(Category, on_delete=CASCADE)
    votes = models.IntegerField(default=0)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name



class Vote(models.Model):
    option = models.ForeignKey(Option, on_delete=CASCADE)
    voter = models.ForeignKey(User, on_delete=CASCADE)
    slug = AutoSlugField(populate_from='option')

# This was commented before i was able to delete the dummy votes and users i created for testing
# the error was__str__ returned a non string 
    def __str__(self):
        return self.voter
    


class Comment(models.Model):
    category = models.ForeignKey(Category, on_delete=CASCADE)
    user = models.ForeignKey(User, on_delete=CASCADE)
    comment = models.TextField()
    created = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.comment




class Contact(models.Model):
    name = models.CharField(max_length=250)
    email = models.EmailField()
    subject = models.CharField(max_length=250)
    message = models.TextField()
    
    def __str__(self):
        return self.name





# # This is supposed to restrict a user from voting 2ice
# class CategoryRequest_Voter(models.Model):
#     voter =models.ForeignKey(User, on_delete=models.CASCADE)
#     published_date = models.DateField(auto_now_add=True, null=True)

#     class Meta:
#         unique_together = ('voter','voted')

#     def publish(self):
#          self.published_date = timezone.now()
#          self.save()



# class User(models.Model):
#     option = models.ForeignKey(Option, on_delete=CASCADE)
#     User = models.ForeignKey(User, unique=True, on_delete=CASCADE)
#     slug = AutoSlugField(populate_from='options')
#     # user = models.ForeignKey(User, on_delete=CASCADE)
#     class Meta:
#         unique_together =('User', 'option')

#     def __str__(self):
#         return self.User

LIFE/Slife/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.forms import PasswordInput

from Slife.models import Comment, Contact

class LoginForm(forms.Form):
    username = forms.CharField(max_length=250)
    password = forms.CharField(widget=PasswordInput)

class RegisterForm(UserCreationForm):
# (forms.Form)
    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise ValidationError('Email Already Exists')
        return email
    class Meta:
            model = User
            fields = ["username","email","password1"]

class CommentForm(forms.ModelForm):
     class Meta:
         model = Comment     
         fields = ['comment']


class ContactForm(forms.ModelForm):
      class Meta:
          model = Contact
          fields = ['name','email','subject','message']                   

LIFE/Slife/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.db.models import Q

from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from rest_framework.decorators import api_view
from rest_framework.response import Response

from LIFE import settings
from Slife.forms import RegisterForm, LoginForm, CommentForm, ContactForm
from Slife.models import Category, Option, Vote
from Slife.serializers import CategorySerializer, OptionSerializer
#from Slife.tokens import activation_token
# Create your views here.



def home(request):
    categories = Category.objects.filter(active=True,views__gte=3000).order_by('-views')
    featured_categories = Category.objects.filter(active=True,featured=True)
    return render(request,'Slife/base.html',{'categories': categories,'featured_categories':featured_categories,'title':'LIFE'})


def all_categories(request):
    categories = Category.objects.filter(active=True)
    return render(request,'Slife/categories.html',{'categories':categories,'title':'LIFE'})


def search(request):
    q = request.GET['q']
    if q:
        categories = Category.objects.filter(name__icontains=q)
        return render(request,'Slife/categories.html',{'categories':categories})
    else:
        return redirect('/')


def options(request,slug):
    category = Category.objects.get(slug=slug)        
    category.views += 1
    category.save()
    options = category.option_set.all().order_by('-votes')
    try:
        for option in options:
            option.has_voted = option.vote_set.filter(voter=request.user).exists()
    except:
        options = category.option_set.all().order_by('-votes')

    form = CommentForm()
    return render(request, 'Slife/options.html', {'options':options,'form':form,'title':'options','category':category})    


def comment(request,slug):
    if not request.user.is_authenticated:
        messages.info(request, 'You have to be logged in to post comments')
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
        if request.method =="POST":
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.category = Category.objects.get(slug=slug)
                comment.user = request.user
                comment.save()
                messages.success(request, ' Comment Posted')
        else:
             return redirect('Slife:options',slug)


def vote(request,slug):
    #if user hasnt logged in before voting 
    if not request.user.is_authenticated:
         messages.info(request,'You have to be logged in to vote.')
         return redirect('%s?next=%s' %(settings.LOGIN_URL, request.path))
    option = Option.objects.get(slug=slug)
    category = option.category

    if Vote.objects.filter(slug=slug, voter_id=request.user.id).exists():
         messages.error(request, 'Sorry! You Already Voted')
         return redirect('Slife:options',category.slug)
    
    else:
         option.votes += 1
         option.save()
         voter = Vote(voter=request.user, option=option)
         #i commented the voter.save because it kep giving object attribute when you cast vote
         voter.save()
         messages.success(request, 'Voted.{} Thanks for your vote.Kindly logout now.'.format(option.votes - 1))
         return redirect('Slife:options', category.slug)

def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            site = get_current_site(request)
            mail_subject = "Confirmation message"
            message = render_to_string('Slife/activate_mail.html',{
                "user":user,
                'domain':site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                #'token': activation_token.make_token(user)

            })
            to_email = form.cleaned_data.get('email')
            to_list = [to_email]
            from_email = settings.EMAIL_HOST_USER
            send_mail(mail_subject,message, from_email, to_list, fail_silently=True)
            messages.success(request,"Thanks for your registration. A confirmation link has been sent to your email")
    else :
        form = RegisterForm()
    return render(request,'Slife/register.html',{'form':form})    


def my_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        username = form['username'].value()
        password = form['password'].value()
        user = authenticate(username=username,password=password)
        if user:
            login(request,user)
            redirect_url = request.GET.get('next','Slife:home')
            return redirect(redirect_url)
        else:
             messages.error(request,'Invalid Username or Password')
    else:
        form = LoginForm()
        return render(request,'Slife/login.html',{'form':form})    

def my_logout(request):
    logout(request)
    messages.success(request,'Logged out successfully')
    return redirect('Slife:login')            

       
   
def contact(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.save()
            messages.success(request,'Your message has been sent')
            return redirect('Slife:contact')
        else:
            messages.error(request,'Error in form.Try Again')
            return redirect('Slife:contact')
    else:
            form = ContactForm()
    return render(request, "Slife/contact.html",{'form':form})    


def about(request):
    return render(request,'Slife/about.html')


@api_view(['GET'])
def api_categories(request):
    query = request.GET.get('q','')
    categories = Category.objects.filter(Q(name__icontains=query)|Q(details__icontains=query))
    serializer = CategorySerializer(categories,many=True)
    return Response(serializer.data)

@api_view(['GET'])    
def api_options(request):
    query = request.GET.get('q','')
    options = Option.objects.filter(name__icontains=query)
    serializer = OptionSerializer(options,many=True)
    return Response(serializer.data)



# class Meta:
#         permssions = (
#             ("view vote","can vote only once"),
#             ("view vote","can vote more than once"),
#         )

        #  messages.success(request, "Voted !!".format(option.votes - 1))
        #  voter.save()
        #  return redirect('Slife:options',category.slug)
        #  messages.success(request,"Voted !!")

LIFE/Slife/templates/Slife/about.html
{% extends "Slife/base.html" %}
{% block title %}about us{% endblock  %}
{% load static %}

{% block content %}
<br><br><br><br><br><br>
<div class="about">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="section_title_container text-center">
						<h2 class="section_title">WELCOME TO SICLIFE VOTING PALTFORM</h2>
						<div class="section_subtitle"><b>This is a voting web application where you can find and get information about the nominees for 
                            best worker for this year.</b></div>
				</div>
			</div>
			<div class="row about_row">

				<!-- About Item -->
				<div class="col-lg-4 about_col about_col_left">
					<div class="about_item">
						<div class="about_item_image"><img src="{% static 'images/maxresdefault.jpg' %}" alt=""></div>
						<div class="about_item_title"><a href="#">Our Stories</a></div>
						<div class="about_item_text">
							<p>Lorem ipsum dolor sit , consectet adipisi elit, sed do eiusmod tempor for enim en consectet adipisi elit, sed do consectet adipisi elit, sed doadesg.</p>
						</div>
					</div>
				</div>

				<!-- About Item -->
				<div class="col-lg-4 about_col about_col_middle">
					<div class="about_item">
						<div class="about_item_image"><img src="{% static 'images/maxresdefault.jpg' %}" alt=""></div>
						<div class="about_item_title"><a href="#">Our Mission</a></div>
						<div class="about_item_text">
							<p>Lorem ipsum dolor sit , consectet adipisi elit, sed do eiusmod tempor for enim en consectet adipisi elit, sed do consectet adipisi elit, sed doadesg.</p>
						</div>
					</div>
				</div>

				<!-- About Item -->
				<div class="col-lg-4 about_col about_col_right">
					<div class="about_item">
						<div class="about_item_image"><img src="{% static 'images/maxresdefault.jpg' %}" alt=""></div>
						<div class="about_item_title"><a href="#">Our Vision</a></div>
						<div class="about_item_text">
							<p>Lorem ipsum dolor sit , consectet adipisi elit, sed do eiusmod tempor for enim en consectet adipisi elit, sed do consectet adipisi elit, sed doadesg.</p>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>
{% endblock %}

LIFE/Slife/templates/Slife/activate_mail.html
<!-- This was just created -->
Hi {{user.username}} Thanks for your registration in SICLIFEVOTE
Please click on the link below to activate your account.
http://{{domain}}{% url 'Slife:activate' uidb64=uid token=token %}

LIFE/Slife/templates/Slife/base.html
<!DOCTYPE html>
{% load static %}
{% load staticfiles %}
{% load bootstrap4 %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

 <title>{% block title %}{{title}}{% endblock title%}</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/shop-homepage.css' %}" rel="stylesheet">

</head>

<body>


  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="/">SICLIFE-VOTE</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
               <li>
                <form class="form-inline my-2 my-lg-0 mr-4" action="{% url 'Slife:search' %}">
                <input class="form-control mr-sm-2" name="q" type="search" placeholder="e.g. best worker" aria-label="Search">
                <button class="btn btn-success " type="submit">Search</button>
            </form>
            </li>
          <li class="nav-item active">
            <a class="nav-link" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
              <li class="nav-item">
            <a class="nav-link" href="{% url 'Slife:categories' %}">All Lists</a>
          </li>
          <li class="nav-item">
             <!-- <a class="nav-link" href="#">Candidates</a>  -->
          </li>
          <li class="nav-item">
             <!-- <a class="nav-link" href="#">Candidates</a>  -->
          </li>
          <li cla  ss="nav-item">
            <a class="nav-link" href="{% url 'Slife:contact' %}">Contact</a>
          </li>
        {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Hi {{user.username}}</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown1">
                             <a class="dropdown-item" href="{% url 'Slife:logout' %}">Logout</a>
                        </div>
                </li>
          {% else %}
                <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                           <a class="dropdown-item" href="{% url 'Slife:login' %}">Login</a>
                            <a class="dropdown-item" href="{% url 'Slife:register' %}">Register</a>  
                        </div> 
                </li>

          {% endif %}

        </ul>
      </div>
    </div>
  </nav>
{% block content %}


  <!-- Page Content -->
  <center>{% bootstrap_messages %}</center>
  <div class="container">

    <div class="row">

      <div class="col-lg-3">
        <div class="list-group">
           <hr>
          <h5>Featured Lists({{featured_categories|length}})</h5>
          {% for category in featured_categories %}
        <b> <a href="{% url 'Slife:options' category.slug %}" class="list-group-item">{{category.name}} ({{category.option_set.all|length}})</a></b>
          {% endfor %}
        </div>

      </div>

      
      <!-- /.col-lg-3 -->
<br>
      <div class="col-lg-9">
          <hr>
          <center> <h5>Most Viewed Lists({{categories|length}})</h5></center>
          <hr>
        <div class="row">

          
 {% for category in categories %}
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="{% url 'Slife:options' category.slug %}"><img width="200" height="200" src="/media/{{categories.image}}" alt=""> </a>
              <div class="card-body">
                <h4 class="card-title"> 

          <a href="{% url 'Slife:options' category.slug %}">{{category.name}} ({{category.option_set.all|length}})</a>
                    <br>
                    <h5> {{category.views}} views</h5>


                </h4>
                <p class="card-text">{{category.details}}</p>
              </div>
             <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9733;</small>
              </div>
            </div>
          </div>
            {% endfor %}
        </div>
        <!-- /.row -->

      </div>

      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  {% endblock content%}
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy
           SICLIFE-GH.com {% now 'Y' %},
           All rights reserved</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

<!---/media/{{category.image}}-->
<!-- disable button -->
<!-- <button type="button" disabled>Click Me!</button>  -->

LIFE/Slife/templates/Slife/candidates.html
{% extends "Slife/base.html" %}
{% block title %}Candidates{% endblock  %}
{% block content %}
<center>
    <br>
<h4>Candidates are based on the number of views for the portal.</h4>
</center>
<ol type="1">
    <div class="row">
{% for c in Slife %}
        {% if c.views >= 20 %}
    <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">

                <div class="card-body">
                     <h4><li>
                  <h4 class="card-title">
                       <img src="/media/{{c.image}}" width="300" height="200">
                    <a href="{% url 'Slife:detail' c.slug %} ">Name:{{c.name}}</a>
                  </h4>
                       <h5>Votes: {{ c.vote }} votes</h5>
                    <h5>Views: {{ c.views }} views</h5>

<!-- 
                    <h5>Website:  <a href="{{ c.website }}">{{ c.website }}</a></h5>
                  <h5>Location: {{ c.location }}</h5> -->
                    <h5>category: {{ c.category }}</h5>
                <a href="{% url 'Slife:detail' c.slug %}" class="btn btn-primary">View More</a>
              </li></h4>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9733;</small>
                </div>
              </div>
            </div>
        {% endif %}
{% empty %}
    <div class="card w-100">
    <div class="card-body">
        <h4>Item not available</h4>
    </div>
    </div>

{% endfor %}
    </div>
</ol>
{% endblock %}

LIFE/Slife/templates/Slife/categories.html
{% extends "Slife/base.html" %}
{% load bootstrap4 %}
<title>{% block title %}{{title}}{% endblock %}</title>
{% block content %}
<br>
<div class="container">
    <div class="row">
        <div class="col-lg-6 offset-lg-3 col-sm-10 offset-sm-1">
            <div class="card my-5">
                <b>&nbsp &nbsp All Lists({{categories|length}})</b>
                 {% for category in categories %}
        <b> <a href="{% url 'Slife:options' category.slug %}" class="list-group-item">{{category.name}} ({{category.option_set.all|length}})</a></b>
          {% endfor %}
        </div>
    </div>
</div>
</div>

{% endblock %}

LIFE/Slife/templates/Slife/contact.html
{% extends "Slife/base.html" %}
{% load bootstrap4 %}
<title>{% block title %}Contact{% endblock %}</title>
{% block content %}
<center>{% bootstrap_messages %}</center>
<br>
<div class="container">
    <div class="row">

        <div class="col-lg-6 offset-lg-3 col-sm-10 offset-sm-1">
            <div class="card my-5">

                <div class="card-header text-center">
                   Login
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <input type="submit" class="btn btn-success text-center w-100 mb-3" value="Send">
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

LIFE/Slife/templates/Slife/login.html
{% extends "Slife/base.html" %}
{% load bootstrap4 %}
<title>{% block title %}user login{% endblock %}</title>
{% block content %}
<center>{% bootstrap_messages %}</center>
<br>
<div class="container">
    <div class="row">

        <div class="col-lg-6 offset-lg-3 col-sm-10 offset-sm-1">
            <div class="card my-5">

                <div class="card-header text-center">
                   Login
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <input type="submit" class="btn btn-success text-center w-100 mb-3" value="Login">
                     <center><a href="{% url 'Slife:password_reset' %}" class="small">Forgot Password ?</a></center>
                       <center> <a href="{% url 'Slife:register' %}" class="small">Register</a></center>


                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

LIFE/Slife/templates/Slife/options.html
{% extends "Slife/base.html" %}
 <title>{% block title %}{{title}}{% endblock title%}</title>
{% load bootstrap4 %}
{% block content %}
<center><br>
     <ol type="1">
          <center>{% bootstrap_messages %}</center>
    {% for option in options %}

     <div class="col-lg-6 col-md-6 mb-6">
              <div class="card h-100">
                <div class="card-body">
                    <b><li>
                  <img src="/media/{{option.image}}" width="400" height="300">
                 <h4>{{option.name}}
                  </h4>
                  <h5 class="card-text">{{ option.details}}</h5>
                      <h5>{{ option.votes }} votes</h5>
                       {% if option.has_voted %}
                             <p class="btn btn-success">Voted</p>
                       {% else %}
                            
                            <form action="{% url 'Slife:vote' option.slug %}" method="post" class="form-disable">
                           {% csrf_token %}
                       <input type="submit" class="btn btn-info" value="Vote" data-submit-value="Voted"> 
                       </form>
                       <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
                       <script src="js/global.js"></script>
                       <!-- <script src="jquery-3.4.1.min.js"></script> -->
                       {% endif %}

                         </li></b>
                </div>
                <div class="card-footer">
                  <small class="text-muted"></small>
                </div>


              </div>
                </div>
         {% empty %}
    <div class="card w-100">
    <div class="card-body">
        <h4>Item not available</h4>
    </div>
    </div>

    {% endfor %}
     </ol>

<!-- <h3>{{ category.comment_set.all|length}} comments</h3>
    <hr>
            {% for c in category.comment_set.all %}
                  <div class="col-lg-6 col-md-6 mb-6">
                     <div class="card-footer text-muted">
                         <b>{{ c.user.username}} </b>&nbsp {{c.created|timesince}} ago
              </div>
              <div class="card-body">
                <p class="card-text">{{ c.comment}}</p>
              </div>

            </div>
            {% endfor %}

    <hr>
   <div class="col-lg-6 col-md-6 mb-6">
            <form method="post" action="/Slife/best-trekking-destination-in-nepal/comment/">
                {% csrf_token %}
                <div class="form-group"><label for="id_comment"><h5>Add a Comment </h5></label><textarea name="comment" cols="40" rows="10" class="form-control" placeholder="Comment" title="" required id="id_comment">
</textarea></div>
            <input type="submit" class="btn btn-success" value="Post Comment">
            </form>
     </div>

 -->

</center>




{% endblock content%}

    

LIFE/Slife/templates/Slife/password_reset.html
{% extends "Slife/base.html" %}
{% load bootstrap4 %}

<title>{% block title %}Password Reset {% endblock %}</title>

{% block content %}
<br>
 <center>{% bootstrap_messages %}</center>
<div class="container">
    <div class="row">
        <div class="col-lg-4 offset-lg-4 col-sm-10 offset-sm-1">
            <div class="card my-5">
                <div class="card-header text-center">
                    Reset
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <input type="submit" class="btn btn-success text-center w-100 mb-3" value="Reset Password">
                        <a href="/" class="float-right small">Home</a>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
<br><br><br><br><br><br><br><br>

{% endblock %}

LIFE/Slife/templates/Slife/password_reset_complete.html
{% extends "Slife/base.html" %}

{% load bootstrap4 %}
<title>{% block title %}Password Reset Complete{% endblock %}</title>

{% block content %}
<br>
<center>{% bootstrap_messages %}</center>
<div class="container">
    <div class="row">
        <div class="col-lg-4 offset-lg-4 col-sm-10 offset-sm-1">
            <div class="card my-5">
                <div class="card-body">
           <h5>Password Changed Successfully !!
           <a href="{% url 'Slife:login' %}">Login</a> </h5>
                </div>
            </div>
        </div>
    </div>
</div>
<br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

LIFE/Slife/templates/Slife/password_reset_confirm.html
{% extends "Slife/base.html" %}

{% load bootstrap4 %}
<title>{% block title %}Password Reset {% endblock %}</title>

{% block content %}
<br>
<center>{% bootstrap_messages %}</center>
<div class="container">
    <div class="row">
        <div class="col-lg-4 offset-lg-4 col-sm-10 offset-sm-1">
            <div class="card my-5">
                <div class="card-header text-center">
                    Reset
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <input type="submit" class="btn btn-success text-center w-100 mb-3" value="Reset Password">
                        <a href="/" class="float-right small">Home</a>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
<br><br><br><br><br><br><br><br>
{% endblock %}